#!/bin/bash

# Clean all CMake files generated by running ćmake manually
# to enable CLion to reload the CMake project.
sudo rm -r CMakeCache.txt
sudo rm -r libCliffordTableausLib.a
sudo rm -r CMakeFiles/
sudo rm -r cmake_install.cmake
sudo rm -r CTestTestfile.cmake
