# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leouscin/Documents/TUM_Studium/SEM_9/ATQC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leouscin/Documents/TUM_Studium/SEM_9/ATQC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leouscin/Documents/TUM_Studium/SEM_9/ATQC/CMakeFiles /home/leouscin/Documents/TUM_Studium/SEM_9/ATQC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leouscin/Documents/TUM_Studium/SEM_9/ATQC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CliffordTableausLib

# Build rule for target.
CliffordTableausLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CliffordTableausLib
.PHONY : CliffordTableausLib

# fast build rule for target.
CliffordTableausLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/build
.PHONY : CliffordTableausLib/fast

#=============================================================================
# Target rules for targets named test_clifford_tableaus

# Build rule for target.
test_clifford_tableaus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_clifford_tableaus
.PHONY : test_clifford_tableaus

# fast build rule for target.
test_clifford_tableaus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_clifford_tableaus.dir/build.make CMakeFiles/test_clifford_tableaus.dir/build
.PHONY : test_clifford_tableaus/fast

#=============================================================================
# Target rules for targets named generate_random_circuits

# Build rule for target.
generate_random_circuits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_random_circuits
.PHONY : generate_random_circuits

# fast build rule for target.
generate_random_circuits/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_random_circuits.dir/build.make CMakeFiles/generate_random_circuits.dir/build
.PHONY : generate_random_circuits/fast

#=============================================================================
# Target rules for targets named clifford_tableau

# Build rule for target.
clifford_tableau: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clifford_tableau
.PHONY : clifford_tableau

# fast build rule for target.
clifford_tableau/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clifford_tableau.dir/build.make CMakeFiles/clifford_tableau.dir/build
.PHONY : clifford_tableau/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clifford_tableau.dir/build.make CMakeFiles/clifford_tableau.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clifford_tableau.dir/build.make CMakeFiles/clifford_tableau.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clifford_tableau.dir/build.make CMakeFiles/clifford_tableau.dir/main.cpp.s
.PHONY : main.cpp.s

src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.o: src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.o
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.o

# target to build an object file
src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.o
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.o

src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.i: src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.i
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.i

# target to preprocess a source file
src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.i
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.i

src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.s: src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.s
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.s

# target to generate assembly for a file
src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.s
.PHONY : src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.cpp.s

src/improved_simulation_of_stabilizer_circuits/subroutines.o: src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.o
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.o

# target to build an object file
src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.o
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.o

src/improved_simulation_of_stabilizer_circuits/subroutines.i: src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.i
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.i

# target to preprocess a source file
src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.i
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.i

src/improved_simulation_of_stabilizer_circuits/subroutines.s: src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.s
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.s

# target to generate assembly for a file
src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.s
.PHONY : src/improved_simulation_of_stabilizer_circuits/subroutines.cpp.s

src/stabilizer_circuit.o: src/stabilizer_circuit.cpp.o
.PHONY : src/stabilizer_circuit.o

# target to build an object file
src/stabilizer_circuit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_circuit.cpp.o
.PHONY : src/stabilizer_circuit.cpp.o

src/stabilizer_circuit.i: src/stabilizer_circuit.cpp.i
.PHONY : src/stabilizer_circuit.i

# target to preprocess a source file
src/stabilizer_circuit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_circuit.cpp.i
.PHONY : src/stabilizer_circuit.cpp.i

src/stabilizer_circuit.s: src/stabilizer_circuit.cpp.s
.PHONY : src/stabilizer_circuit.s

# target to generate assembly for a file
src/stabilizer_circuit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_circuit.cpp.s
.PHONY : src/stabilizer_circuit.cpp.s

src/stabilizer_tableau.o: src/stabilizer_tableau.cpp.o
.PHONY : src/stabilizer_tableau.o

# target to build an object file
src/stabilizer_tableau.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_tableau.cpp.o
.PHONY : src/stabilizer_tableau.cpp.o

src/stabilizer_tableau.i: src/stabilizer_tableau.cpp.i
.PHONY : src/stabilizer_tableau.i

# target to preprocess a source file
src/stabilizer_tableau.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_tableau.cpp.i
.PHONY : src/stabilizer_tableau.cpp.i

src/stabilizer_tableau.s: src/stabilizer_tableau.cpp.s
.PHONY : src/stabilizer_tableau.s

# target to generate assembly for a file
src/stabilizer_tableau.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CliffordTableausLib.dir/build.make CMakeFiles/CliffordTableausLib.dir/src/stabilizer_tableau.cpp.s
.PHONY : src/stabilizer_tableau.cpp.s

tests/generate_random_circuits.o: tests/generate_random_circuits.cpp.o
.PHONY : tests/generate_random_circuits.o

# target to build an object file
tests/generate_random_circuits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_random_circuits.dir/build.make CMakeFiles/generate_random_circuits.dir/tests/generate_random_circuits.cpp.o
.PHONY : tests/generate_random_circuits.cpp.o

tests/generate_random_circuits.i: tests/generate_random_circuits.cpp.i
.PHONY : tests/generate_random_circuits.i

# target to preprocess a source file
tests/generate_random_circuits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_random_circuits.dir/build.make CMakeFiles/generate_random_circuits.dir/tests/generate_random_circuits.cpp.i
.PHONY : tests/generate_random_circuits.cpp.i

tests/generate_random_circuits.s: tests/generate_random_circuits.cpp.s
.PHONY : tests/generate_random_circuits.s

# target to generate assembly for a file
tests/generate_random_circuits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_random_circuits.dir/build.make CMakeFiles/generate_random_circuits.dir/tests/generate_random_circuits.cpp.s
.PHONY : tests/generate_random_circuits.cpp.s

tests/test_improved_stabilizer_tableau.o: tests/test_improved_stabilizer_tableau.cpp.o
.PHONY : tests/test_improved_stabilizer_tableau.o

# target to build an object file
tests/test_improved_stabilizer_tableau.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_clifford_tableaus.dir/build.make CMakeFiles/test_clifford_tableaus.dir/tests/test_improved_stabilizer_tableau.cpp.o
.PHONY : tests/test_improved_stabilizer_tableau.cpp.o

tests/test_improved_stabilizer_tableau.i: tests/test_improved_stabilizer_tableau.cpp.i
.PHONY : tests/test_improved_stabilizer_tableau.i

# target to preprocess a source file
tests/test_improved_stabilizer_tableau.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_clifford_tableaus.dir/build.make CMakeFiles/test_clifford_tableaus.dir/tests/test_improved_stabilizer_tableau.cpp.i
.PHONY : tests/test_improved_stabilizer_tableau.cpp.i

tests/test_improved_stabilizer_tableau.s: tests/test_improved_stabilizer_tableau.cpp.s
.PHONY : tests/test_improved_stabilizer_tableau.s

# target to generate assembly for a file
tests/test_improved_stabilizer_tableau.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_clifford_tableaus.dir/build.make CMakeFiles/test_clifford_tableaus.dir/tests/test_improved_stabilizer_tableau.cpp.s
.PHONY : tests/test_improved_stabilizer_tableau.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... CliffordTableausLib"
	@echo "... clifford_tableau"
	@echo "... generate_random_circuits"
	@echo "... test_clifford_tableaus"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.o"
	@echo "... src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.i"
	@echo "... src/improved_simulation_of_stabilizer_circuits/improved_stabilizer_tableau.s"
	@echo "... src/improved_simulation_of_stabilizer_circuits/subroutines.o"
	@echo "... src/improved_simulation_of_stabilizer_circuits/subroutines.i"
	@echo "... src/improved_simulation_of_stabilizer_circuits/subroutines.s"
	@echo "... src/stabilizer_circuit.o"
	@echo "... src/stabilizer_circuit.i"
	@echo "... src/stabilizer_circuit.s"
	@echo "... src/stabilizer_tableau.o"
	@echo "... src/stabilizer_tableau.i"
	@echo "... src/stabilizer_tableau.s"
	@echo "... tests/generate_random_circuits.o"
	@echo "... tests/generate_random_circuits.i"
	@echo "... tests/generate_random_circuits.s"
	@echo "... tests/test_improved_stabilizer_tableau.o"
	@echo "... tests/test_improved_stabilizer_tableau.i"
	@echo "... tests/test_improved_stabilizer_tableau.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

